# Generated by Django 4.1.3 on 2023-04-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paid_amount',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
